version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - db-data:/var/www/html/app/db/
    ports:
      - "8080:80"
    command: bash -c "chown -R www-data:www-data /var/www/html/app && exec apache2-foreground"

volumes:
  db-data: